os:
  - linux

language: cpp

compiler:
  - gcc

install:
  - cpanm --installdeps --cpanfile ./.travis/cpanfile ./.travis

script:
  - make
  - cd .travis; prove

addons:
  apt:
    packages:
    - gcc-4.8
    - g++-4.8
